#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

  CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_USER WITH ENCODING='UTF8' OWNER=$DB_USER;
  ALTER DATABASE $DB_USER SET search_path = public;

EOSQL
